import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex justify-center min-h-screen">
        <div className="w-full max-w-2xl p-8 space-y-4">{children}</div>
      </body>
    </html>
  );
}
